CREATE TABLE CART 
(
  CART_NUM NUMBER(5, 0) NOT NULL 
, PRODUCT_NUM NUMBER(5, 0) NOT NULL 
, USER_ID VARCHAR2(200 BYTE) NOT NULL 
, PRODUCT_COUNT NUMBER(3, 0) NOT NULL 
, PRODUCT_CHECK NUMBER(1, 0) DEFAULT 1 
, CONSTRAINT SYS_C007057 PRIMARY KEY 
  (
    CART_NUM 
  )
);

CREATE TABLE COUPON 
(
  COUPON_NUM NUMBER(5, 0) NOT NULL 
, USER_ID VARCHAR2(200 BYTE) NOT NULL 
, DISCOUNT_RATE NUMBER(3, 0) NOT NULL 
, ISSUE_DATE VARCHAR2(200 BYTE) NOT NULL 
, COUPON_STATUS VARCHAR2(20 BYTE) DEFAULT 0 NOT NULL 
);

CREATE TABLE PRODUCT 
(
  PRODUCT_NUM NUMBER(5, 0) NOT NULL 
, CATEGORY_NUM NUMBER(5, 0) NOT NULL 
, PRODUCT_NAME VARCHAR2(100 BYTE) NOT NULL 
, PRODUCT_PRICE NUMBER(7, 0) NOT NULL 
, PRODUCT_STOCK NUMBER(10, 0) DEFAULT 0 
, PRODUCT_DESC VARCHAR2(200 BYTE) DEFAULT '' 
, PRODUCT_HITS NUMBER(7, 0) DEFAULT 0 
, PRODUCT_LIKE NUMBER(7, 0) DEFAULT 0 
, PRODUCT_DATE DATE DEFAULT SYSDATE 
, PRODUCT_GRADE NUMBER(2, 1) DEFAULT 0 
, PRODUCT_SALE NUMBER(12, 0) DEFAULT 0 
, PRODUCT_SELLCOUNT NUMBER(10, 0) DEFAULT 0 
, PRODUCT_ORIGIN VARCHAR2(30 BYTE) 
, PRODUCT_EXP VARCHAR2(50 BYTE) 
, STORE_SNUM NUMBER(5, 0) 
, CONSTRAINT SYS_C007030 PRIMARY KEY 
  (
    PRODUCT_NUM 
  )
);

CREATE TABLE PRODUCT_CATEGORY 
(
  CATEGORY_NUM NUMBER(5, 0) NOT NULL 
, CATEGORY_MAIN VARCHAR2(50 BYTE) NOT NULL 
, CATEGORY_DETAIL VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT SYS_C007036 PRIMARY KEY 
  (
    CATEGORY_NUM 
  )
);

CREATE TABLE PRODUCT_DETAIL_IMAGEFILE 
(
  FILE_NUMBER NUMBER(2, 0) NOT NULL 
, PRODUCT_NUM NUMBER(5, 0) NOT NULL 
, ORIGIN_FILE_NAME VARCHAR2(500 BYTE) 
, STORED_FILE_NAME VARCHAR2(500 BYTE) 
, CONSTRAINT SYS_C007048 PRIMARY KEY 
  (
    FILE_NUMBER 
  , PRODUCT_NUM 
  )
);

CREATE TABLE PRODUCT_LIKE 
(
  USER_ID VARCHAR2(200 BYTE) NOT NULL 
, PRODUCT_NUM NUMBER(5, 0) NOT NULL 
);

CREATE TABLE PRODUCT_REPLY 
(
  REPLY_NUMBER NUMBER(5, 0) 
, PRODUCT_NUM NUMBER(5, 0) 
, USER_ID VARCHAR2(200 BYTE) 
, CONTENT VARCHAR2(3000 BYTE) 
, REPORTING_DATE DATE DEFAULT sysdate 
, REPLY_ORIGIN_NUMBER NUMBER(5, 0) 
, REPLY_DEPTH NUMBER(5, 0) DEFAULT 0 
, REPLY_YN NUMBER(5, 0) DEFAULT 0 
);

CREATE TABLE PRODUCT_REVIEW 
(
  PRODUCT_NUM NUMBER(5, 0) NOT NULL 
, USER_ID VARCHAR2(200 BYTE) NOT NULL 
, CONTENT VARCHAR2(3000 BYTE) 
, REPORTING_DATE DATE DEFAULT sysdate 
, REVIEW_GRADE NUMBER(1, 0) 
);

CREATE TABLE PRODUCT_REVIEW_IMAGEFILE 
(
  FILE_NUMBER NUMBER(2, 0) NOT NULL 
, PRODUCT_NUM NUMBER(5, 0) NOT NULL 
, USER_ID VARCHAR2(200 BYTE) NOT NULL 
, ORIGIN_FILE_NAME VARCHAR2(500 BYTE) 
, STORED_FILE_NAME VARCHAR2(500 BYTE) 
, CONSTRAINT SYS_C007042 PRIMARY KEY 
  (
    FILE_NUMBER 
  , PRODUCT_NUM 
  , USER_ID 
  )
);

CREATE TABLE PRODUCT_THUMB_IMAGEFILE 
(
  FILE_NUMBER NUMBER(2, 0) NOT NULL 
, PRODUCT_NUM NUMBER(5, 0) NOT NULL 
, ORIGIN_FILE_NAME VARCHAR2(500 BYTE) 
, STORED_FILE_NAME VARCHAR2(500 BYTE) 
, CONSTRAINT SYS_C007045 PRIMARY KEY 
  (
    FILE_NUMBER 
  , PRODUCT_NUM 
  )
);

CREATE TABLE SELLER 
(
  SELLER_ID VARCHAR2(200 BYTE) NOT NULL 
, SELLER_PW VARCHAR2(200 BYTE) 
, SELLER_NAME VARCHAR2(200 BYTE) 
, SELLER_PHONE VARCHAR2(200 BYTE) 
, SELLER_EMAIL VARCHAR2(200 BYTE) 
, USER_ROLE NUMBER(1, 0) 
, BUSINESS_LICENSE VARCHAR2(200 BYTE) 
, BUSINESS_ADDRESS VARCHAR2(200 BYTE) 
, CONSTRAINT SYS_C007220 PRIMARY KEY 
  (
    SELLER_ID 
  )
);

CREATE TABLE STORE 
(
  STORE_SNUM NUMBER(5, 0) NOT NULL 
, SELLER_ID VARCHAR2(200 BYTE) NOT NULL 
, STORE_SNAME VARCHAR2(200 BYTE) NOT NULL 
, STORE_PRODUCT_COUNT NUMBER(5, 0) DEFAULT 0 
, STORE_SELLCOUNT NUMBER(10, 0) DEFAULT 0 
, STORE_SALES NUMBER(15, 0) DEFAULT 0 
, CONSTRAINT SYS_C007052 PRIMARY KEY 
  (
    STORE_SNUM 
  )
);

CREATE TABLE SURVEY 
(
  SURVEY_NUM VARCHAR2(200 BYTE) 
, SURVEY_BIGO VARCHAR2(2000 BYTE) 
, CATEGORY_NUM VARCHAR2(200 BYTE) 
, SURVEY_AGE VARCHAR2(200 BYTE) 
, SURVEY_GENDER VARCHAR2(200 BYTE) 
);

CREATE TABLE SURVEY_DETAIL 
(
  USER_ID VARCHAR2(200 BYTE) 
, SURVEY_NUM VARCHAR2(200 BYTE) 
, CATEGORY_NUM VARCHAR2(200 BYTE) 
, SURVEY_CHECK VARCHAR2(200 BYTE) 
, SURVEY_AGE VARCHAR2(200 BYTE) 
);

CREATE TABLE USER_ORDER 
(
  ORDER_NUM NUMBER(10, 0) NOT NULL 
, USER_ID VARCHAR2(200 BYTE) NOT NULL 
, DELIVERY_DATE DATE DEFAULT sysdate 
, DELIVERY_NAME VARCHAR2(200 BYTE) 
, DELIVERY_ADDRESS1 VARCHAR2(2000 BYTE) 
, DELIVERY_ADDRESS2 VARCHAR2(2000 BYTE) 
, DELIVERY_ADDRESS3 VARCHAR2(2000 BYTE) 
, DELIVERY_PHONE VARCHAR2(200 BYTE) 
, DELIVERY_REQUEST VARCHAR2(2000 BYTE) 
, COUPON_SALE NUMBER(10, 0) 
, GRADE_SALE NUMBER(10, 0) 
, DELIVERY_FEE NUMBER(10, 0) 
, POINT NUMBER(10, 0) 
, TOTAL_PAYMENT NUMBER(10, 0) 
, COUPON_NUM NUMBER(10, 0) 
, DISCOUNT_RATE NUMBER(10, 0) 
, DELIVERY_STATUS VARCHAR2(20 BYTE) DEFAULT 0 
);

CREATE TABLE USER_ORDER_PRODUCT 
(
  ORDER_NUM NUMBER(10, 0) 
, PRODUCT_NUM VARCHAR2(200 BYTE) 
, PRODUCT_NAME VARCHAR2(200 BYTE) 
, PRODUCT_COUNT VARCHAR2(200 BYTE) 
, PRODUCT_PRICE VARCHAR2(200 BYTE) 
, PRODUCT_TOTPRICE VARCHAR2(200 BYTE) 
, DELIVERY_STATUS VARCHAR2(20 BYTE) DEFAULT 0 
);

CREATE TABLE USER_SUBSCRIBE 
(
  SUBSCRIBE_NUM NUMBER(10, 0) NOT NULL 
, USER_ID VARCHAR2(200 BYTE) NOT NULL 
, SUBSCRIBE_DAY VARCHAR2(200 BYTE) NOT NULL 
, DELIVERY_DATE DATE DEFAULT sysdate 
, DELIVERY_NAME VARCHAR2(200 BYTE) 
, DELIVERY_ADDRESS1 VARCHAR2(2000 BYTE) 
, DELIVERY_ADDRESS2 VARCHAR2(2000 BYTE) 
, DELIVERY_ADDRESS3 VARCHAR2(2000 BYTE) 
, DELIVERY_PHONE VARCHAR2(200 BYTE) 
, DELIVERY_REQUEST VARCHAR2(2000 BYTE) 
, COUPON_SALE NUMBER(10, 0) 
, GRADE_SALE NUMBER(10, 0) 
, DELIVERY_FEE NUMBER(10, 0) 
, POINT NUMBER(10, 0) 
, TOTAL_PAYMENT NUMBER(10, 0) 
, COUPON_NUM NUMBER(10, 0) 
, DISCOUNT_RATE NUMBER(10, 0) 
, DELIVERY_STATUS VARCHAR2(20 BYTE) DEFAULT 0 
);

CREATE TABLE USER_SUBSCRIBE_PRODUCT 
(
  SUBSCRIBE_NUM NUMBER(10, 0) 
, PRODUCT_NUM VARCHAR2(200 BYTE) 
, PRODUCT_NAME VARCHAR2(200 BYTE) 
, PRODUCT_COUNT VARCHAR2(200 BYTE) 
, PRODUCT_PRICE VARCHAR2(200 BYTE) 
, PRODUCT_TOTPRICE VARCHAR2(200 BYTE) 
);

CREATE TABLE USER_TABLE 
(
  USER_ID VARCHAR2(200 BYTE) 
, USER_PWD VARCHAR2(200 BYTE) 
, USER_NAME VARCHAR2(200 BYTE) 
, USER_PHONE VARCHAR2(200 BYTE) 
, USER_ADDRESS1 VARCHAR2(200 BYTE) 
, USER_ADDRESS2 VARCHAR2(200 BYTE) 
, USER_ADDRESS3 VARCHAR2(200 BYTE) 
, USER_EMAIL VARCHAR2(200 BYTE) 
, USER_BIRTHDAY DATE 
, USER_GENDER VARCHAR2(200 BYTE) 
, USER_NICKNAME VARCHAR2(200 BYTE) 
, EMAIL_CHECK VARCHAR2(20 BYTE) DEFAULT 1 
, USER_ROLE NUMBER(2, 0) DEFAULT 0 
, USER_GRADE NUMBER(2, 0) DEFAULT 0 
, USER_TOTPURCHASE NUMBER(10, 0) DEFAULT 0 
, USER_POINT NUMBER(10, 0) DEFAULT 0 
, USER_INSERTDATE DATE DEFAULT SYSDATE 
);

CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE COUPON_NUM_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE ORDER_NUM_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE STORE_SNUM_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE SUBSCRIBE_NUM_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;